# Generated by Django 4.0.3 on 2022-03-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_regist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(max_length=10)),
                ('Product_name', models.CharField(max_length=100)),
                ('Date_Time', models.DateField()),
                ('Phone', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=100)),
                ('Customer', models.CharField(max_length=200)),
                ('Source', models.CharField(max_length=100)),
                ('Inventos_Cust', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
