# Generated by Django 4.0.3 on 2022-04-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_device_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNo', models.CharField(max_length=10)),
                ('ProductModel', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=100)),
                ('Customername', models.CharField(max_length=100)),
                ('customerNo', models.CharField(max_length=10)),
                ('Delivery_update', models.CharField(max_length=10)),
                ('userText', models.TextField()),
            ],
        ),
    ]
